[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta:"

[project]
name = "designbuilder_schema"
version = "0.1"
description = "A Python package for reading and processing DBXML fileformat"
authors = [{ name = "Bartlomiej Tokarzewski", email = "bartlomiej.tokarzewski@gmail.com"}]
dependencies = [
    "pydantic >= 2",
    "xmltodict >= 0.13",
    "fire >= 0.5"
]

readme = "README.md"
#license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

[project.urls]
Homepage = "https://github.com/tokarzewski/designbuilder_schema"
"Bug Tracker" = "https://github.com/tokarzewski/designbuilder_schema/issues"

[tool.setuptools]
packages = ["designbuilder_schema"]


[project.optional-dependencies]
dev = ["pytest", "coverage", "flake8", "black"]

[tool.pytest.ini_options]
pythonpath = ["C:/GitHub/designbuilder_schema/designbuilder_schema"]
testpaths = ["tests"]

[tool.coverage.run]
source = ["designbuilder_schema"]

[tool.flake8]
max-line-length = 88
exclude = [".git", "__pycache__", "docs", "build", "dist"]

[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']
